# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  overload_config = debug

else ifeq ($(config),release)
  overload_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := overload

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

overload:
ifneq (,$(overload_config))
	@echo "==== Building overload ($(overload_config)) ===="
	@${MAKE} --no-print-directory -C . -f overload.make config=$(overload_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f overload.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   overload"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"