name: Auto Deploy Doxy Gen Documentation

on:
  push:
    branches:
      - main
      - indev

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Compile Doxygen Docs
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
