name: Auto Deploy Doxy Gen Documentation

on:
  push:
    branches:
      - main
      - indev

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Doxygen Docs
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
