on:
  push:
    branches:
      - main
      - indev
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-22.04

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Dependincies
        run: |
          sudo apt update && sudo apt install -y build-essential libglfw3-dev libglew-dev libglm-dev libassimp-dev
          sudo apt install -y p7zip-full liblua5.4-dev
          sudo cp /usr/include/lua5.4/lua.hpp /usr/include/
          sudo cp /usr/include/lua5.4/lua.h /usr/include/
          
      - name: Install Premake5
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xvf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin
          premake5 --version

      - name: Generate Premake Files
        run: premake5 gmake2

      - name: Build Project
        run: make -j
